easy_admin:
    entities:
        Alertes:
            class: App\Entity\Alert
            disabled_actions: ['new']
            list:
                fields: ['id', 'number', 'lat', 'lng', 'age', 'sex', 'symptoms']
            form:
                fields:
                    - {property: 'number'}
                    - {property: 'symptoms'}
                    - {property: 'infos'}
                    - {property: 'lat'}
                    - {property: 'lng'}
                    -   property: 'status'
                        type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                        type_options:
                            mapped: true
                            expanded: true
                            multiple: false
                            choices: {suspect: 'Suspect', confirmé: 'Confirmé', mort: 'Mort', rétabli: 'Rétabli'}

