version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/maker-bundle
    versions:
    - 1.28.0
    - 1.29.1
    - 1.30.1
  - dependency-name: symfony/string
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/translation
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/expression-language
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
    - 1.12.1
  - dependency-name: symfony/mailer
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
